# Generated by Django 3.2.9 on 2021-11-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UssdUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField()),
                ('transaction_pin', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
