# Generated by Django 3.2.9 on 2021-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loandemo', '0002_loanmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
