# Generated by Django 3.2.9 on 2021-11-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loandemo', '0003_loanmodel_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussduser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
