# Generated by Django 3.2.9 on 2021-11-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loandemo', '0004_alter_ussduser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussduser',
            name='phone_number',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
