# Generated by Django 3.2.9 on 2021-11-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loandemo', '0005_alter_ussduser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='plan',
            field=models.CharField(choices=[('weekly', '1'), ('monthly', '2')], default='weekly', max_length=20),
        ),
    ]
